export default function getActivityAPI() {
    return ({ 
        all:[
            {
                title: "Cordially convinced did incommode existence",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f668068d4ca5.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"Easy to distinguish. In a free hour, when our power of choice is untrammelled and...",
                comment:5,
                viewed:96,
            },
            {
                title: "At ourselves direction believing do the departure",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f667ff239f07.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"author",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:25,
            },
            {
                title: "Situation admitting promotion at or to perceived...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6533d506cf9.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Material confined likewise it humanity raillery...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f664480e44f8.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:125,
            },
            {
                title: "Situation admitting promotion at or to perceived...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6533d506cf9.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Style never met and those among great",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6643d5ba7bf.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:124,
            }
        ],
    clothes:[
        {
            title: "Situation admitting promotion at or to perceived...",
            imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6533d506cf9.jpg",
            linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
            author:"admin",
            type:"img",
            date:"Sep 19, 2020",
            description:"",
            comment:5,
            viewed:96,
        },
        {
            title: "Style never met and those among great",
            imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6643d5ba7bf.jpg",
            linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
            author:"admin",
            type:"img",
            date:"Sep 19, 2020",
            description:"",
            comment:5,
            viewed:124,
        }
    ]
    })
}