export default function getActivityAPI() {
    return ({
        all:[
            {
                title: "Is allowance instantly strangers applauded",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6531af69888.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                date:"Sep 19, 2020",
                type:"Photography",
                description:"Difficulty on insensible reasonable in. From as went he they. Preference themselves...",
                comment:0,
                viewed:384,
            },
            {
                title: "Decisively advantages nor expression untrammelled",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f666f7511daf.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"author",
                type: "video",
                typeIcon:"play",
                date:"Sep 19, 2020",
                description:"These cases are perfectly simple and easy to distinguish. In a free hour, when our...",
                comment:1,
                viewed:204,
            },
            {
                title: "Expound the actual teachings of the great explorer...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6685ad1141f.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type: "img",
                typeIcon:"play",
                date:"Sep 19, 2020",
                description:"",
                comment:1,
                viewed:105,
            },
            {
                title: "Greatly hearted has who believe",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f666c39d5bd9.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"music",
                typeIcon:"play",
                date:"Sep 19, 2020",
                description:"",
                comment:2,
                viewed:294,
            },
            {
                title: "Expound the actual teachings of the great explorer...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6685ad1141f.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                typeIcon:"play",
                date:"Sep 19, 2020",
                description:"",
                comment:2,
                viewed:248,
            },
            {
                title: "Greatly hearted has who believe",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f666c39d5bd9.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"music",
                typeIcon:"play",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:456,
            },
            {
                title: "Carriage quitting securing be appetite it clared",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6641aaea7fb.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"author",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:2,
                viewed:568,
            },
            {
                title: "Anyone who loves or pursues or desires to obtain...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f663f7e0b324.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"author",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:2,
                viewed:24,
            },            
        ]
    })
}