export default function getActivityAPI() {
    return ({ 
        all:[
            {
                title: "Sunrise Shadows Over the Philippine Sea",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6502b596068.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"As the International Space Station orbited more than 200 miles above our home planet,...",
                comment:5,
                viewed:96,
            },
            {
                title: "Sweet pineapple success for the Northern Territory",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64fe27345dc.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"As the International Space Station orbited more than 200 miles above our home planet,...",
                comment:5,
                viewed:96,
            },
            {
                title: "Spitzer Captures Stellar Family Portrait",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f650309a7a28.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Hubble Views Edge of Stellar Blast",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6502bf90d35.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Sunrise Shadows Over the Philippine Sea",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6502b596068.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Spitzer Captures Stellar Family Portrait",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f650309a7a28.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Hubble Views Edge of Stellar Blast",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6502bf90d35.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Spitzer Captures Stellar Family Portrait",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f650309a7a28.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Hubble Views Edge of Stellar Blast",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6502bf90d35.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Skylab Commander Jerry Carr Trains for His Mission",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6502a0bb25d.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            }            
        ],
        nasa:[
            {
                title: "Sunrise Shadows Over the Philippine Sea",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6502b596068.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Spitzer Captures Stellar Family Portrait",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f650309a7a28.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Hubble Views Edge of Stellar Blast",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6502bf90d35.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Skylab Commander Jerry Carr Trains for His Mission",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6502a0bb25d.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            }
        ],
        theIndependent:[
            {
                title: "PS5: How to increase your chances of getting...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64fa34cd47e.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Trump's TikTok ban violates the first amendment,...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64f988dda00.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Xbox announces exactly when Series X and S pre-orders...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64f589f3dda.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "The fashion show must go on: Empty catwalks and...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64f569be075.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            }
        ],
        wired:[
            {
                title: "'Spellbreak' Conjures Up a Unique Spin on Battle...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64fa1e6253f.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "How to Break Out of Your Social Media Echo Chamber",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64f4fd33305.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "The Nintendo 3DS' Surprisingly Social Legacy",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64f4fba8643.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Netflix's 'Ratched' Is a Plea for Mental Health...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64f4fa23d7c.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            }
        ],
        abcNews:[
            {
                title: "Sweet pineapple success for the Northern Territory",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64fe27345dc.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Mutated bananas could hold the key to Australia's...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64fe2f45e35.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Bushfire destroys pioneering Qld banana plantation",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64fe2b340fc.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "'Demonised' farmers rage against reef regulations...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f64fe1f95a61.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            }
        ]
    })
}