export default function getActivityAPI() {
    return ( 
        [
            {
                title: "At ourselves direction believing do the departure",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f667ff15cc20.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                type:"Fashion",
                typeIcon:"none",
                author:"admin", 
                date:"Sep 19, 2020",
                description:"",
                comment:2,
                viewed:248,
            },
            {
                title: "Implementing these goals requires a careful examination",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f65cc838a0af.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"Photography",
                typeIcon:"none",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:456,
            },
            {
                title: "Greatly hearted has who believe",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f666c398b3b1.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"author",
                type:"Photography",
                typeIcon:"music",
                date:"Sep 19, 2020",
                description:"",
                comment:2,
                viewed:24,
            },
            {
                title: "Sportsman do offending supported extremity breakfast by listening",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f667dc6b7401.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"Videos",
                typeIcon:"play",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Through weakness of will, which is the same as saying through",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f667ee20cd73.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"Nature",
                typeIcon:"none",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "At ourselves direction believing do the departure",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f667ff15cc20.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"Fashion",
                typeIcon:"none",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Implementing these goals requires a careful examination",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f65cc838a0af.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"Photography",
                typeIcon:"none",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Greatly hearted has who believe",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f666c398b3b1.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"Photography",
                typeIcon:"music",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Sportsman do offending supported extremity breakfast by listening",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f667dc6b7401.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"Videos",
                typeIcon:"play",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Through weakness of will, which is the same as saying through",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f667ee20cd73.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"Nature",
                typeIcon:"none",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "At ourselves direction believing do the departure",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_600x460_5f667ff15cc20.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"Fashion",
                typeIcon:"none",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
        ]
    )
}