export default function getActivityAPI() {
    return ({ 
        all:[
            {
                title: "Through weakness of will, which is the same as...",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f667ee28012f.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"There anyone who loves or pursues or desires to obtain pain of itself, because it...",
                comment:5,
                viewed:96,
            },
            {
                title: "Charms of pleasure of the moment",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f66705d8a15b.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"music",
                date:"Sep 19, 2020",
                description:"There anyone who loves or pursues or desires to obtain pain of itself, because it...",
                comment:5,
                viewed:96,
            },
            {
                title: "Far concluded not his something extremity",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f666e7eb1797.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"video",
                date:"Sep 19, 2020",
                description:"There anyone who loves or pursues or desires to obtain pain of itself, because it...",
                comment:5,
                viewed:96,
            },
            {
                title: "Society excited by cottage private an it esteems",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6642b6e79b2.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"author",
                type:"img",
                date:"Sep 19, 2020",
                description:"There anyone who loves or pursues or desires to obtain pain of itself, because it...",
                comment:5,
                viewed:96,
            },
            {
                title: "Charms of pleasure of the moment",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f667ee28012f.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"There anyone who loves or pursues or desires to obtain pain of itself, because it...",
                comment:5,
                viewed:96,
            },
            {
                title: "Charms of pleasure of the moment",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f66705d8a15b.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"music",
                date:"Sep 19, 2020",
                description:"There anyone who loves or pursues or desires to obtain pain of itself, because it...",
                comment:5,
                viewed:96,
            },
            {
                title: "Society excited by cottage private an it esteems",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6642b6e79b2.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Folly was these three and songs arose whose",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f664119e44a7.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:52,
            }
        ],
        nature:[
            {
                title: "Charms of pleasure of the moment",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f667ee28012f.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Charms of pleasure of the moment",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f66705d8a15b.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"music",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Society excited by cottage private an it esteems",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f6642b6e79b2.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Folly was these three and songs arose whose",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f664119e44a7.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"admin",
                type:"img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:52,
            }
        ],
        place:[
            {
                title: "Far concluded not his something extremity",
                imgLink:"https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f666e7eb1797.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author:"author",
                type:"music",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
            {
                title: "Two before narrow not relied how except moment...",
                imgLink: "https://varient.codingest.com/uploads/images/2020/09/image_380x226_5f66416ad00f3.jpg",
                linkPage:"/effect-twenty-indeed-beyond-for-not-had-county",
                author: "admin",
                type: "img",
                date:"Sep 19, 2020",
                description:"",
                comment:5,
                viewed:96,
            },
        ]
    })
}