export const CHANGE_COLOR = "CHANGE_COLOR"
export const CHANGE_THEME_MODE = "CHANGE_THEME_MODE"
// HomePage constant
export const GET_LIFESTYLE_REQUEST = "GET_LIFESTYLE_REQUEST"
export const GET_LIFESTYLE_SUCCESS = "GET_LIFESTYLE_SUCCESS"
export const GET_LIFESTYLE_FAILURE = "GET_LIFESTYLE_FAITURE"

export const GET_FASHION_REQUEST = "GET_FASHION_REQUEST"
export const GET_FASHION_SUCCESS = "GET_FASHION_SUCCESS"
export const GET_FASHION_FAILURE = "GET_FASHION_FAITURE"

export const GET_QUIZZES_REQUEST = "GET_QUIZZES_REQUEST"
export const GET_QUIZZES_SUCCESS = "GET_QUIZZES_SUCCESS"
export const GET_QUIZZES_FAILURE = "GET_QUIZZES_FAITURE"

export const GET_TRAVEL_REQUEST = "GET_TRAVEL_REQUEST"
export const GET_TRAVEL_SUCCESS = "GET_TRAVEL_SUCCESS"
export const GET_TRAVEL_FAILURE = "GET_TRAVEL_FAITURE"

export const GET_RSSNEWS_REQUEST = "GET_RSSNEWS_REQUEST"
export const GET_RSSNEWS_SUCCESS = "GET_RSSNEWS_SUCCESS"
export const GET_RSSNEWS_FAILURE = "GET_RSSNEWS_FAITURE"

export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST"
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS"
export const GET_VIDEOS_FAILURE = "GET_VIDEOS_FAITURE"

export const GET_SLIDEFEATURES_REQUEST = "GET_SLIDEFEATURES_REQUEST"
export const GET_SLIDEFEATURES_SUCCESS = "GET_SLIDEFEATURES_SUCCESS"
export const GET_SLIDEFEATURES_FAILURE = "GET_SLIDEFEATURES_FAITURE"

export const GET_FEATURES_RIGHT_REQUEST = "GET_FEATURES_RIGHT_REQUEST"
export const GET_FEATURES_RIGHT_SUCCESS = "GET_FEATURES_RIGHT_SUCCESS"
export const GET_FEATURES_RIGHT_FAILURE = "GET_FEATURES_RIGHT_FAITURE"

export const GET_NEWTICKER_REQUEST = "GET_NEWTICKER_REQUEST"
export const GET_NEWTICKER_SUCCESS = "GET_NEWTICKER_SUCCESS"
export const GET_NEWTICKER_FAILURE = "GET_NEWTICKER_FAITURE"

export const GET_LASTPOST_REQUEST = "GET_LASTPOST_REQUEST"
export const GET_LASTPOST_SUCCESS = "GET_LASTPOST_SUCCESS"
export const GET_LASTPOST_FAILURE = "GET_LASTPOST_FAITURE"

export const GET_POPULAR_POSTS_REQUEST = "GET_POPULAR_POSTS_REQUEST"
export const GET_POPULAR_POSTS_SUCCESS = "GET_POPULAR_POSTS_SUCCESS"
export const GET_POPULAR_POSTS_FAILURE = "GET_POPULAR_POSTS_FAITURE"

export const GET_RECOMMENDED_POSTS_REQUEST = "GET_RECOMMENDED_POSTS_REQUEST"
export const GET_RECOMMENDED_POSTS_SUCCESS = "GET_RECOMMENDED_POSTS_SUCCESS"
export const GET_RECOMMENDED_POSTS_FAILURE = "GET_RECOMMENDED_POSTS_FAITURE"

export const GET_RANDOM_POSTS_REQUEST = "GET_RANDOM_POSTS_REQUEST"
export const GET_RANDOM_POSTS_SUCCESS = "GET_RANDOM_POSTS_SUCCESS"
export const GET_RANDOM_POSTS_FAILURE = "GET_RANDOM_POSTS_FAITURE"

export const GET_TAGS_REQUEST = "GET_TAGS_REQUEST"
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS"
export const GET_TAGS_FAILURE = "GET_TAGS_FAITURE"

export const GET_VOTING_POLL_REQUEST = "GET_VOTING_POLL_REQUEST"
export const GET_VOTING_POLL_SUCCESS = "GET_VOTING_POLL_SUCCESS"
export const GET_VOTING_POLL_FAILURE = "GET_VOTING_POLL_FAITURE"

export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILURE = "GET_POST_FAITURE"


export const typeColors = {
    FASHION: "#30b333",
    LIFE_STYLE: "#e44e4e",
    VIDEOS: "#bf448e",
    NATURE: "#00acd8",
    QUIZZES: "#f9ab00",
    TRAVEL: "#00acd8",
    RSS_NEWS: "#607d8b",
    LAST_POSTS:"#161616"
}

export const homePage = "/varent"